server:
  port: 8080
  servlet:
    context-path: /taskhub

app:
  security:
    open: true
  db:
    recreate: false   # set true only when you want a full reset in dev

spring:

  h2:
    console:
      enabled: true
      path: /h2-console
      
  datasource:
    url: jdbc:h2:mem:taskhub;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: SA
    password:
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    # keep clean disabled by default; DevFlywayConfig only cleans when app.db.recreate=true
    clean-disabled: true
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always