spring:
  application:
    name: taskhub-backend

server:
  port: 8080
  servlet:
    context-path: /taskhub-cloud
  # Respect X-Forwarded-* from Hostpoint (keeps URLs correct behind proxy)
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info" ]
  endpoint:
    health:
      show-details: "when-authorized"  # valid for Spring Boot 3.x/3.5.x

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html

logging:
  level:
    root: INFO
    org.springframework.web: INFO