server:
  servlet:
    context-path: /taskhub

app:
  security:
    open: false   # PROD should normally require auth

spring:
  datasource:
    url: jdbc:mariadb://YOUR_DB_HOST:3306/taskhub?useUnicode=true&characterEncoding=utf8
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc.time_zone: UTC
        format_sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,threaddump,httpexchanges
  endpoint:
    health:
      show-details: when_authorized

# (Optional) bootstrap a simple basic user if you want quick testing in PROD:
# spring:
#   security:
#     user:
#       name: client
#       password: change-me