# ============================================================
# TEST profile (unit/integration tests)
# ============================================================

server:
  port: 0
  servlet:
    context-path: /taskhub

spring:
  application:
    name: taskhub-backend-test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:taskhub_test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
  flyway:
    enabled: false

# Actuator: expose only what we need for the smoke test
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when-authorized

# OpenAPI / Swagger — standard springdoc endpoints
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: error